PJT/PJT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PJT/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:pk>", views.profile, name="profile"),
    path("userlist/", views.userlist, name="userlist"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
    path("delete/", views.delete, name="delete"),
]

PJT/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),  # 메인 페이지
    path("movie/", views.movie, name="movie"),  # 영화 등록
    path("movie/<int:movie_pk>", views.moviedetail, name="moviedetail"),  # 영화 상세보기
    path("movie/<int:movie_pk>/update", views.movie_update, name="movie_update"),
    path(
        "<int:movie_pk>/movie_delete/", views.movie_delete, name="movie_delete"
    ),  # 영화 삭제
    path("search/", views.search, name="search"),
    path("<int:movie_pk>/create", views.create, name="create"),  # 리뷰 작성
    path("<int:review_pk>/", views.detail, name="detail"),  # 리뷰 보기
    path("<int:review_pk>/update", views.update, name="update"),  # 리뷰 수정
    path("<int:review_pk>/delete/", views.delete, name="delete"),  # 리뷰 삭제
    path("<int:pk>/comments/", views.comment_create, name="comment_create"),  # 댓글 작성
    path(
        "<int:review_pk>/comments/<int:comment_pk>/delete/",
        views.comment_delete,
        name="comment_delete",
    ),  # 댓글 삭제
]

PJT/templates/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% bootstrap_css %}
  {% block css %}{% endblock css %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
  <title>Movie Space</title>
</head>

<body class="background-img">
  <nav class="navbar navbar-expand-lg navbar-dark bg-black py-3">
    <div class="container-fluid w-100">
      <a class="navbar-brand ms-5" href="{% url 'articles:index' %}">
        <img class="" src="{% static 'images/logo.png' %}" alt="logo" height="65">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item mx-2">
            <a class="nav-link" href="{% url 'articles:index' %}">Movies</a>
          </li>
          <li class="nav-item mx-2">
            <a class="nav-link" href="{% url 'accounts:userlist' %}">Users</a>
          </li>
        </ul>
        <!-- 로그인한 경우 -->
        {% if user.is_authenticated %}
        <ul class="navbar-nav">
          <li class="nav-item mx-2">
            <a class="nav-link" href="{% url 'accounts:profile' user.pk %}">Hello,
              {{ request.user.username }}</a>
          </li>
          <a class="nav-link mx-2" href="{% url 'accounts:logout' %}">Logout</a>
        </ul>
        <!-- guest -->
        {% else %}
        <ul class="navbar-nav">
          <li class="nav-item mx-2">
            <a class="nav-link" href="{% url 'accounts:login' %}">Hello, Guest</a>
          </li>
          <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
          <a class="nav-link" href="{% url 'accounts:signup' %}">SingUp</a>
        </ul>
        {% endif %}

        <form class="d-flex me-5" role="search" method="GET" action="{% url 'articles:search' %}">
          {% csrf_token %}
          <input class="form-control mx-2" type="search" placeholder="Movie Search" name="search" aria-label="Search">
          <button class="btn btn-outline-light" type="submit">Search</button>
        </form>

      </div>
    </div>
  </nav>

  {% if messages %}
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }}">
    {{ message }}
  </div>
  {% endfor %}
  {% endif %}

  {% block content %}{% endblock %}
  {% bootstrap_javascript %}
  <footer class="text-center">
    <div class="position-fixed bottom-0 w-100 d-flex justify-content-center">
      <div class="bg-black py-2 col-5 rounded-5 border border-dark">
        <p class="text-white m-0">Web-django PJT, by KP JS SJ</p>
      </div>
    </div>
    <div class="m-5">
      <br>
    </div>
  </footer>
</body>

</html>