PJT/PJT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PJT/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("<int:pk>", views.profile, name="profile"),
    path("userlist/", views.userlist, name="userlist"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),
    path("delete/", views.delete, name="delete"),
]

PJT/accounts/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

PJT/accounts/forms.py
# accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
        )


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = (
            "email",
            "first_name",
            "last_name",
        )

PJT/accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm

from django.contrib.auth import (
    login as auth_login,
    logout as auth_logout,
    update_session_auth_hash,
)
from django.contrib.auth.decorators import login_required
from .models import User
from django.contrib import messages
import random


def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            form.save()
            auth_login(request, user)
            messages.success(request, "회원가입이 완료되었습니다.")
            return redirect("articles:index")
    else:
        form = CustomUserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            messages.success(request, "로그인 되었습니다.")
            return redirect("articles:index")
    else:
        form = AuthenticationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/login.html", context)


@login_required
def logout(request):
    auth_logout(request)
    messages.success(request, "로그아웃 되었습니다.")
    return redirect("articles:index")


@login_required
def profile(request, pk):
    user = User.objects.get(pk=pk)
    profile = ['https://cdn.pixabay.com/photo/2021/04/05/15/55/neptune-6153867_960_720.png',
    'https://cdn.pixabay.com/photo/2021/04/05/15/48/earth-6153854_960_720.png',
    'https://cdn.pixabay.com/photo/2021/04/05/15/52/jupiter-6153859_960_720.png',
    'https://cdn.pixabay.com/photo/2021/04/05/15/44/venus-6153849_960_720.png',
    'https://cdn.pixabay.com/photo/2021/04/05/15/53/saturn-6153860_960_720.png',
    'https://cdn.pixabay.com/photo/2021/04/05/15/44/mercury-6153848_960_720.png',
    'https://cdn.pixabay.com/photo/2021/04/05/15/48/moon-6153855_960_720.png',
    'https://cdn.pixabay.com/photo/2021/04/05/15/52/mars-6153858_960_720.png',
    'https://cdn.pixabay.com/photo/2021/04/05/15/54/uranus-6153865_960_720.png']

    profile_image = random.choice(profile)
    context = {
        "profile_image": profile_image,
        "user": user,
    }
    return render(request, "accounts/profile.html", context)


@login_required
def userlist(request):
    users = User.objects.all()
    profile = ['https://cdn.pixabay.com/photo/2021/04/05/15/55/neptune-6153867_960_720.png',
    'https://cdn.pixabay.com/photo/2021/04/05/15/48/earth-6153854_960_720.png',
    'https://cdn.pixabay.com/photo/2021/04/05/15/52/jupiter-6153859_960_720.png',
    'https://cdn.pixabay.com/photo/2021/04/05/15/44/venus-6153849_960_720.png',
    'https://cdn.pixabay.com/photo/2021/04/05/15/53/saturn-6153860_960_720.png',
    'https://cdn.pixabay.com/photo/2021/04/05/15/44/mercury-6153848_960_720.png',
    'https://cdn.pixabay.com/photo/2021/04/05/15/48/moon-6153855_960_720.png',
    'https://cdn.pixabay.com/photo/2021/04/05/15/52/mars-6153858_960_720.png',
    'https://cdn.pixabay.com/photo/2021/04/05/15/54/uranus-6153865_960_720.png']

    profile_image = random.choice(profile)
 
    context = {
        "profile_image": profile_image,
        "users": users,
    }
    return render(request, "accounts/userlist.html", context)


@login_required
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, "회원정보 수정이 완료되었습니다.")
            return redirect("articles:index")
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/update.html", context)


@login_required
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("articles:index")
    else:
        form = PasswordChangeForm(request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/change_password.html", context)


@login_required
def delete(request):
    request.user.delete()
    auth_logout(request)
    messages.success(request, "회원 탈퇴가 완료되었습니다.")
    return redirect("articles:index")

PJT/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% block content %}
  {% load django_bootstrap5 %}
{% comment %} 
  <div class="container d-flex justify-content-center py-5">
    <div class="card col-6">
      <h1 class="text-center my-5 fs-3 fw-bold text-white">Reset password</h1>
      <div class="card-body">
        <form action="{% url 'accounts:update' %}" method="POST" class="text-white">
          {% csrf_token %}
          {% bootstrap_form form %}
          <div class="d-grid gap-2">
            <button class="btn btn-primary mt-5 mb-2" type="submit">Reset Password</button>
            <a class="btn btn-outline-secondary text-white" href="{% url 'accounts:profile' user.pk %}" role="button">Back</a>
          </div>
        </form>
      </div>
    </div>
  </div> {% endcomment %}

  <div class="container d-flex justify-content-center py-5">
    <div class="card col-6 review-detail">
      <h1 class="text-center mt-5 mb-3 fs-3 fw-bold text-white">Reset Password</h1>
      <div class="card-body">
        <form action="{% url 'accounts:update' %}" method="POST" class="text-dark px-5 py-3">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="text-end mt-4">
                <input type="submit" class="btn btn-warning" value="Save">
                <a class=" btn btn-dark ms-3" href="{% url 'accounts:profile' user.pk %}" role="button">Back</a>
            </div>
        </form>
      </div>
    </div>
  </div>

{% endblock content %}

PJT/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
  {% load django_bootstrap5 %}
  <div class="container d-flex justify-content-center py-5">
    <div class="card col-6 review-detail">
        {% comment %} <div class="review-detail rounded-4 shadow-lg p-5"> {% endcomment %}
      <h1 class="text-center mt-5 fs-3 fw-bold text-white">Login</h1>
      <div class="card-body">
        <form action="{% url 'accounts:login' %}" method="POST" class="text-dark px-5 py-3">
          {% csrf_token %}
          {% bootstrap_form form %}
          <div class="d-grid gap-2">
            <button class="btn btn-warning mt-5 mb-2" type="submit">Login</button>
            <a class="btn btn-outline-warning text-black" href="{% url 'accounts:signup' %}" role="button">Create Account</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

PJT/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}
  {% load django_bootstrap5 %}

  <div class="container d-flex flex-column align-items-center py-5">
    <div class="card mt-5 mb-4 border border-light" style="width: 25rem;">
      <div class="card-header border border-light text-white opacity-75">
        <h5 class="fs-3 fw-bold text-center my-1">
          {{ user.username }}
        </h5>
      </div>
      <div class="card-body d-flex justify-content-center">
        <img src="{{ profile_image }}" class="card-img-top rounded-1" style="width: 20rem; height: 20rem;" alt="...">
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <i class="bi bi-hash me-2"></i>
          User No.
          {{ user.pk }}</li>
        <li class="list-group-item">
          <i class="bi bi-person-fill me-2"></i>
          {{ user.first_name }}
          {{ user.last_name }}</li>
        <li class="list-group-item">
          <i class="bi bi-envelope-fill me-2"></i>
          {{ user.email }}</li>
        <li class="list-group-item">
          <i class="bi bi-calendar-check-fill me-2"></i>
          joined at
          {{ user.date_joined|date:'Y-m-d H:i' }}</li>
      </ul>
    </div>
    <!-- Button -->
    {% if request.user == user %}
      <div class="mb-5 d-flex justify-content-end">
        <div class="btn-group" role="group">
          <button type="button" class="btn btn-warning dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            Edit
          </button>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" href="{% url 'accounts:update' %}" role="button">Edit My Info</a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'accounts:change_password' %}" role="button">Change Password</a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li>
              <a class="dropdown-item text-danger" href="{% url 'accounts:delete' %}" role="button">Delete Account</a>
            </li>
          </ul>
        </div>
        <a class=" btn btn-secondary mx-3" href="{% url 'accounts:userlist' %}" role="button">Back</a>
      </div>
    {% else %}
      <div class="d-flex justify-content-end">
        <a class=" btn btn-secondary mx-3" href="{% url 'accounts:userlist' %}" role="button">Back</a>
      </div>
    {% endif %}
  </div>
</div>
{% endblock content %}

PJT/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
  {% load django_bootstrap5 %}

  {% comment %} <div class="container py-5">
    <div class="review-detail rounded-4 shadow-lg p-5">
      <h1 class="text-white fw-bolder text-center">Sign Up</h1>
      <form action="{% url 'accounts:signup' %}" method="POST" class="text-white opacity-80">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="text-end">
          <input type="submit" value="submit" class="px-3 py-2 rounded-1">
        </div>
      </form>
    </div>
  </div> {% endcomment %}

  <div class="container d-flex justify-content-center py-5">
    <div class="card col-6 review-detail">
        {% comment %} <div class="review-detail rounded-4 shadow-lg p-5"> {% endcomment %}
      <h1 class="text-center mt-5 fs-3 fw-bold text-white">Sign Up</h1>
      <div class="card-body">
        <form action="{% url 'accounts:signup' %}" method="POST" class="text-dark px-5 py-3">
          {% csrf_token %}
          {% bootstrap_form form %}
          <div class="text-end">
            <input type="submit" class="btn btn-warning mt-2" value="Join">
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

PJT/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% block content %}
  {% load django_bootstrap5 %}
  {% comment %} <div class="container py-5">
    <h1 class="text-white opacity-50 pb-3">
      Edit Profile
    </h1>
    <form action="{% url 'accounts:update' %}" method="POST" class="text-white opacity-75">
      {% csrf_token %}
      {% bootstrap_field form.email %}
      {% bootstrap_field form.first_name %}
      {% bootstrap_field form.last_name %}
      <div class="text-end">
        <input type="submit" value="submit" class="text-dark px-3 py-2 rounded-1">
      </div>
    </form>
  </div> {% endcomment %}

  <div class="container d-flex justify-content-center py-5">
    <div class="card col-6 review-detail">
        {% comment %} <div class="review-detail rounded-4 shadow-lg p-5"> {% endcomment %}
      <h1 class="text-center mt-5 mb-3 fs-3 fw-bold text-white">Edit Profile</h1>
      <div class="card-body">
        <form action="{% url 'accounts:update' %}" method="POST" class="text-dark px-5 py-3">
          {% csrf_token %}
          {% bootstrap_field form.email %}
          {% bootstrap_field form.first_name %}
          {% bootstrap_field form.last_name %}
          <div class="text-end mt-4">
            <input type="submit" class="btn btn-warning" value="Save">
            <a class=" btn btn-dark ms-3" href="{% url 'accounts:profile' user.pk %}" role="button">Back</a>
          </div>
        </form>
      </div>
    </div>
          
  </div>
{% endblock content %}

PJT/accounts/templates/accounts/userlist.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
  <div class="container py-5">
    <div class="text-center text-white">
      <h2>User List</h2>
    </div>
    <div class="row row-cols-1 row-cols-md-2">
      {% for user in users %}
        <div class="col g-4 text-center">
          <div class="card h-100 m-4 text-white">
            <div class="card-body">
              <img src="{{ profile_image }}" style="width: 10rem; height:10rem;" class="shadow-lg mb-3">
              <h4 class="card-subtitle my-2">{{ user.last_name }}{{ user.first_name }}</h4>
              <hr>
              <div class="p-3 text-white text-bg-white opacity-75">
                <h4 class="card-subtitle my-2 text-warning">
                  {{ user.email }}</h4>
                <p class="card-text m-0">user no.
                  {{ user.pk }}</p>
                <p class="card-text fs-6">joined at
                  {{ user.date_joined|date:'Y-m-d H:i:s' }}</p>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock content %}