PJT/PJT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PJT/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),  # 메인 페이지
    path("movie/", views.movie, name="movie"),  # 영화 등록
    path("movie/<int:movie_pk>", views.moviedetail, name="moviedetail"),  # 영화 상세보기
    path("movie/<int:movie_pk>/update", views.movie_update, name="movie_update"),
    path(
        "<int:movie_pk>/movie_delete/", views.movie_delete, name="movie_delete"
    ),  # 영화 삭제
    path("search/", views.search, name="search"),
    path("<int:movie_pk>/create", views.create, name="create"),  # 리뷰 작성
    path("<int:review_pk>/", views.detail, name="detail"),  # 리뷰 보기
    path("<int:review_pk>/update", views.update, name="update"),  # 리뷰 수정
    path("<int:review_pk>/delete/", views.delete, name="delete"),  # 리뷰 삭제
    path("<int:pk>/comments/", views.comment_create, name="comment_create"),  # 댓글 작성
    path(
        "<int:review_pk>/comments/<int:comment_pk>/delete/",
        views.comment_delete,
        name="comment_delete",
    ),  # 댓글 삭제
]

PJT/articles/models.py
from email.policy import default
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from multiselectfield import MultiSelectField


# Create your models here.


class Movie(models.Model):
    title = models.CharField(max_length=30)
    summary = models.TextField()
    director = models.CharField(max_length=20)
    runningtime = models.IntegerField(default=50)
    releasedate = models.DateField(null=True)
    genrelist = (
        ("SF", "SF"),
        ("드라마", "드라마"),
        ("액션", "액션"),
        ("모험", "모험"),
        ("판타지", "판타지"),
        ("멜로", "멜로"),
        ("코미디", "코미디"),
        ("느와르", "느와르"),
        ("히어로", "히어로"),
        ("공포", "공포"),
        ("하이틴", "하이틴"),
    )
    jenre = MultiSelectField(
        choices=genrelist,
        min_choices=1,
        max_choices=3,
    )
    image = ProcessedImageField(
        blank=True,
        upload_to="images/",
        processors=[ResizeToFill(720, 480)],
        format="JPEG",
        options={"quality": 100},
    )
    thumbnail = ProcessedImageField(
        upload_to="images/",
        blank=True,
        processors=[ResizeToFill(700, 1000)],
        format="JPEG",
        options={"quality": 80},
    )


class Review(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    grade = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(10)]
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

PJT/articles/forms.py
from django import forms
from .models import Review, Comment, Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = "__all__"
        labels = {
            'jenre': 'Genre',
        }
        widgets = {
            "runningtime": forms.NumberInput(
                attrs={
                    "maxlength": "3",
                    "min": "1",
                }
            ),
            "releasedate": forms.DateInput(
                format=("%m/%d/%Y"),
                attrs={
                    "class": "form-control",
                    "placeholder": "Select a date",
                    "type": "date",
                },
            ),
        }


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = [
            "title",
            "content",
            "grade",
        ]
        widgets = {
            "grade": forms.NumberInput(
                attrs={
                    "maxlength": "1",
                    "max": "10",
                    "min": "1",
                }
            ),
        }


class CommentForm(forms.ModelForm):
    content = forms.CharField(
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "댓글을 남겨보세요 💬",
            }
        ),
    )

    class Meta:
        model = Comment
        fields = [
            "content",
        ]

PJT/articles/views.py
from django.shortcuts import render, redirect
from .models import Review, Comment, Movie
from .forms import ReviewForm, CommentForm, MovieForm
from django.contrib.auth.decorators import login_required
from django.db.models import Avg, Max, Min, Sum

# Create your views here.


def index(request):
    reviews = Review.objects.all()
    movies = Movie.objects.order_by("-pk")
    context = {
        "reviews": reviews,
        "movies": movies,
    }
    return render(request, "articles/index.html", context)


@login_required
def create(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    if request.method == "POST":
        create_form = ReviewForm(request.POST)
        if create_form.is_valid():
            review = create_form.save(commit=False)
            review.user = request.user
            review.movie = movie
            create_form.save()
            return redirect("articles:moviedetail", movie_pk)

    else:
        create_form = ReviewForm()

    context = {
        "create_form": create_form,
    }

    return render(request, "articles/create.html", context)


@login_required
def delete(request, review_pk):
    Review.objects.get(pk=review_pk).delete()
    return redirect("articles:index")


@login_required
def detail(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    comment_form = CommentForm()
    comments = review.comment_set.all()
    context = {
        "review": review,
        "comment_form": comment_form,
        "comments": comments,
    }

    return render(request, "articles/detail.html", context)


@login_required
def update(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.method == "POST":
        create_form = ReviewForm(request.POST, instance=review)
        if create_form.is_valid():
            create_form.save()
            return redirect("articles:detail", review_pk)
    else:
        create_form = ReviewForm(instance=review)

    context = {
        "create_form": create_form,
    }

    return render(request, "articles/create.html", context)


@login_required
def comment_create(request, pk):
    review = Review.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.review = review
        comment.user = request.user
        comment.save()
    return redirect("articles:detail", pk)


@login_required
def comment_delete(request, review_pk, comment_pk):
    Comment.objects.get(pk=comment_pk).delete()
    return redirect("articles:detail", review_pk)


@login_required
def movie(request):
    if request.method == "POST":
        movie_form = MovieForm(request.POST, request.FILES)
        if movie_form.is_valid():
            movie_form.save()
            return redirect("articles:index")
    else:
        movie_form = MovieForm()

    context = {
        "movie_form": movie_form,
    }

    return render(request, "articles/movie.html", context)


@login_required
def moviedetail(request, movie_pk):
    reviews = Review.objects.filter(movie=movie_pk)
    movie = Movie.objects.get(pk=movie_pk)
    grade = reviews.aggregate(avg=Avg("grade"))
    cnt = reviews.count()
    avg = "리뷰 없음"
    star = ""
    if grade["avg"]:
        if grade["avg"] > 9.8:
            star = "★★★★★"
        elif grade["avg"] > 8.8:
            star = "★★★★☆"
        elif grade["avg"] > 7.8:
            star = "★★★★"
        elif grade["avg"] > 6.8:
            star = "★★★☆"
        elif grade["avg"] > 5.8:
            star = "★★★"
        elif grade["avg"] > 4.8:
            star = "★★☆"
        elif grade["avg"] > 3.8:
            star = "★★"
        elif grade["avg"] > 2.8:
            star = "★☆"
        elif grade["avg"] > 1.8:
            star = "★"
        elif grade["avg"] > 0.8:
            star = "☆"
        else:
            avg = ""
        avg = round(grade["avg"] / 2, 1)
    context = {
        "movie": movie,
        "reviews": reviews,
        "star": star,
        "avg": avg,
        "cnt": cnt,
    }
    return render(request, "articles/moviedetail.html", context)


@login_required
def movie_delete(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    movie.delete()
    return redirect("articles:index")


def movie_update(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    if request.method == "POST":
        movie_form = MovieForm(request.POST, request.FILES, instance=movie)
        if movie_form.is_valid():
            movie_form.save()
            return redirect("articles:moviedetail", movie_pk)
    else:
        movie_form = MovieForm(instance=movie)

    context = {
        "movie_form": movie_form,
    }

    return render(request, "articles/movie.html", context)


def search(request):
    if request.method == "GET":
        searched = request.GET.get("search")
        if searched:
            movies = Movie.objects.filter(title__contains=searched)
            context = {
                "search": searched,
                "movies": movies,
            }
        else:
            context = {
                "search": searched,
            }
        return render(request, "articles/search.html", context)
    else:
        return render(request, "articles/index.html")

PJT/articles/templates/articles/create.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block css %}{% endblock css %}

{% block content %}
  {% comment %} <div class="container">
    <div class="text-center text-white">
      <h1>Review</h1>
    </div>
    <form action="" method="POST" class="text-white">
      {% csrf_token %}
      {% bootstrap_form create_form %}
      <div class="text-end">
        <input type="submit" class="btn btn-dark" value="글 작성">
      </div>
    </form>
    </div> {% endcomment %}

    <div class="container d-flex justify-content-center py-5">
      <div class="card col-9 review-detail">
          {% comment %} <div class="review-detail rounded-4 shadow-lg p-5"> {% endcomment %}
        <h1 class="text-center mt-5 mb-3 fs-3 fw-bold text-white">Review</h1>
        <div class="card-body">
          <form action="" method="POST" class="text-dark px-5 py-3">
            {% csrf_token %}
            {% bootstrap_form create_form %}
            <div class="text-end mt-4">
              <input type="submit" class="btn btn-warning" value="Save">
              {% comment %} <a class=" btn btn-dark ms-3" href="{% url 'articles:moviedetail' movie.pk %}" role="button">Back</a> {% endcomment %}
            </div>
          </form>
        </div>
      </div>
    </div>
  {% endblock content %}

PJT/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block css %}{% endblock css %}

{% block content %}

  <div class="container d-flex flex-column justify-content-center my-5">
    <div class="review-detail p-5 rounded-4 shadow-lg">
      <div class="d-flex justify-content-between">
      <h2 class="text-white font-space">{{ review.title }}</h2>
        {% if request.user == review.user %}
          <a href="{% url 'articles:update' review.pk %}" class="btn btn-outline-dark mt-5">Edit</a>
        {% endif %}
      </div>
      <i></i>
      <hr>
      <div class="d-flex justify-content-between align-middle">
        <p class="text-white">
          writer :
          {{ review.user }}</p>
        {% if review.created_at == review.updated_at %}
          <p class="text-white">{{ review.created_at }}</p>
        {% else %}
          <p class="text-white">{{ review.updated_at }}
            (수정됨)</p>
        {% endif %}
      </div>
      <hr class="mt-0">
      <pre class="fs-6 text-white ">{{ review.content}}</pre>
      {% comment %} <div class="d-flex justify-content-end my-3">
        {% if request.user == review.user %}
          <a href="{% url 'articles:update' review.pk %}" class="btn btn-outline-dark mt-5">Edit</a>
        {% endif %}
      </div> {% endcomment %}
      <hr>
      <form action="{% url 'articles:comment_create' review.pk %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form comment_form %}
        <div class="text-end"><input class="btn btn-warning" type="submit" value="Comment"></div>
      </form>
      <h5 class="text-white">comments ({{ comments|length }})</h5>
      <hr>
      <ul class="list-group list-group-flush rounded-2">
        {% for comment in comments %}
          <li class="list-group-item align-middle">
            <div class="d-flex justify-content-between align-items-center">
              <p class="card-text text-muted m-2">{{ comment.user }}</p>
              <p class="card-text text-muted pt-3">{{ comment.created_at }}</p>

            </div>
            <div class="d-flex justify-content-between align-items-center m-2">
              <p class="">
                {{ comment.content }}
              </p>
              {% if request.user == comment.user %}
                <form action="{% url 'articles:comment_delete' review.pk comment.pk %}" method="POST">
                  {% csrf_token %}
                  <input class="text-danger bg-white ms-3 border-1 border-danger text-decoration-none rounded-2" type="submit" value="삭제">
                </form>
              {% endif %}
            </div>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock content %}

PJT/articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container text-center py-5">
  <h2 class="text-center mb-5 text-white">All Movies</h2>
  <div class="row g-4 g-sm-4 g-md-5 row-cols-1 row-cols-sm-2 row-cols-md-3">
    {% for movie in movies %}
    <div class="col mt-5 mb-4">
      <div class="card h-100 border border-5 border-warning shadow-lg">
        <a class="text-decoration-none" href="{% url 'articles:moviedetail' movie.pk %}">
          <h5 class="card-header fw-bold py-3 bg-black text-light">
            {{ movie.title }}
          </h5>
          {% if movie.thumbnail %}
          <div class="card-hover">
            <img src="{{ movie.thumbnail.url }}" class="card-img-top" alt="{{ movie.thumbnail }}">
          </div>
          {% else %}
          <div class="card-hover">
            <img src="{% static 'images/empty.jpg' %}" class="card-img-top" alt="...">
          </div>
          {% endif %}
        </a>
      </div>
    </div>
    {% endfor %}
  </div>
  <div class="d-flex justify-content-end mt-4 fixed-bottom">
    <a class="btn btn-warning m-5 fw-bold" href="{% url 'articles:movie' %}">Add Movie</a>
  </div>
</div>

{% endblock %}

PJT/articles/templates/articles/movie.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block css %}{% endblock css %}

{% block content %}
  {% comment %} <div class="container d-flex justify-content-center align-items-center">
    <div class="bg-white rounded-5">
      <h2>Add Movie</h2>
      <form action="" method="POST" enctype="multipart/form-data" class="text-dark p-5">
        {% csrf_token %}
        {% bootstrap_form movie_form %}
        <input type="submit" class="btn btn-warning" value="글 작성">
      </form>
    </div>
  </div> {% endcomment %}

  <div class="container d-flex justify-content-center py-5">
    <div class="card col-9 review-detail">
      <h1 class="text-center mt-5 fs-3 fw-bold text-white">Add Movie</h1>
      <div class="card-body">
        <form action="" method="POST" enctype="multipart/form-data" class="text-dark px-5 py-3">
          {% csrf_token %}
          {% bootstrap_form movie_form %}
          <div class="text-end mt-4">
            <input type="submit" class="btn btn-warning" value="Save">
            <a class=" btn btn-dark ms-3" href="{% url 'articles:index' %}" role="button">Back</a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

PJT/articles/templates/articles/moviedetail.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block css %}{% endblock css %}

{% block content %}
<div class="container my-5">
  <div class="review-back py-1 px-5 rounded-4">
    {% if movie.image %}
    <div class="d-flex justify-content-center">
      <img src="{{ movie.image.url }}" class="container">
    </div>
    {% endif %}
    <section class="my-5 d-flex justify-content-center">
      <div class="container mx-1">
        <div class="d-flex justify-content-between align-items-center">
          <h1 class="text-white fw-bolder m-0">{{ movie.title }}</h1>
          <div>
            <a class=" btn btn-outline-light m-2" href="{% url 'articles:movie_update' movie.pk %}">Edit</a>
            <a class=" btn btn-outline-danger m-2" href=" {% url 'articles:movie_delete' movie.pk %} ">Delete</a>
          </div>
        </div>
        <hr class=" mt-1 text-white">
        <p class="text-white">
          <span>평점
            <span class="text-warning fw-bold">{{ star }}</span>
            <span class="small">{{ avg }}({{ cnt }})</span>
          </span>
          <span>·</span>
          <span>{{ movie.jenre }}</span>
          <span>·</span>
          <span>{{ movie.runningtime }}분</span>
          <span>·</span>
          <span>감독 :
            {{ movie.director }}</span>
        </p>
        <p class="text-white">
          <span>개봉일 :
            {{ movie.releasedate }}</span>
        </p>
        <div class="d-flex">
          <div class="text-center me-5 my-2">
            <a class="p-0 btn btn-lg border-0 text-white" href="">
              <span class="bi bi-share fs-2"></span>
              <p class="small">Share</p>
            </a>
          </div>
          <div class="text-center me-4 my-2">
            <a class="p-0 btn btn-lg border-0 text-white" href="">
              <span class="bi bi-heart fs-2"></span>
              <p class="small">Like</p>
            </a>
          </div>
        </div>
        <p class="text-white">{{ movie.summary }}</p>
      </div>
    </section>
  </div>
  <div class="d-flex justify-content-end mb-4 mt-5">
    <a class="btn btn-warning" href="{% url 'articles:create' movie.pk %}">Add Review</a>
    <a class="btn btn-dark ms-3" href="{% url 'articles:index' %}">Back</a>
  </div>
  {% if reviews %}
  <div class="review-back py-3 px-5 rounded-4">
    {% for review in reviews %}
    <div class="d-flex justify-content-between mt-5">
      <a class="text-white text-decoration-none" href="{% url 'articles:detail' review.pk %}">
        <h4 class="f">{{ review.title }}
        </h4>
        <span class="text-white fs-6">
          <i class="bi bi-star-fill text-warning"></i>
          {{ review.grade }}
        </span>
      </a>
      <a href="{% url 'articles:delete' review.pk %}" class="text-white small text-decoration-none">
        <i class="bi bi-x-lg"></i>
      </a>
    </div>
    <hr class="fw-bolder">
    {% endfor %}
  </div>
  {% endif %}
</div>
</div>
{% endblock content %}

PJT/articles/templates/articles/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container text-center py-5">
    {% if movies %}
    <h2 class="text-center mb-5 text-white">Search result "{{ search }}"</h2>
    <div class="row g-4 g-sm-4 g-md-5 row-cols-1 row-cols-sm-2 row-cols-md-3">
        {% for movie in movies %}
        <div class="col mt-5 mb-4">
            <div class="card h-100 border border-5 border-warning shadow-lg">
                <a class="text-decoration-none" href="{% url 'articles:moviedetail' movie.pk %}">
                    <h5 class="card-header fw-bold py-3 bg-black text-light">
                        {{ movie.title }}
                    </h5>
                    {% if movie.thumbnail %}
                    <div class="card-hover">
                        <img src="{{ movie.thumbnail.url }}" class="card-img-top" alt="{{ movie.thumbnail }}">
                    </div>
                    {% else %}
                    <div class="card-hover">
                        <img src="{% static 'images/empty.jpg' %}" class="card-img-top" alt="...">
                    </div>
                    {% endif %}
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <h2 class="text-center mb-5 text-white">No results were founded "{{ search }}"</h2>
    <p class="text-center mb-5 text-white">Check that you have entered it correctly, including spaces.</p>
    {% endif %}

</div>

{% endblock %}